import { Nunito } from "next/font/google";
import Navbar from "../components/Navbar/page";
import Footer from "../components/Footer/page";
import GlobalState from "../context";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={nunito.className}>
        <GlobalState>
          <Navbar />
          <main>{children}</main>

          <Footer />
        </GlobalState>
      </body>
    </html>
  );
}
