import { Nunito } from "next/font/google";
import Navbar from "../components/Navbar/page";
import Footer from "../components/Footer/page";
import GlobalState from "../context";
import Navbars from "../components/Navbars/Navbars";
import React from "react";
// import main from "./manifest.json";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.0.0/css/all.css"
          integrity="sha384-3B6NwesSXE7YJlcLI9RpRqGf2p/EgVH8BgoKTaUrmKNDkHPStTQ3EyoYjCGXaOTS"
          // crossorigin="anonymous"
        />
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
        {/* <link rel="manifest" href={main} /> */}
      </head>
      <body className={nunito.className}>
        <GlobalState>
          <React.Fragment>
            <Navbars />
          </React.Fragment>
          <main>{children}</main>

          <Footer />
        </GlobalState>
      </body>
    </html>
  );
}
